### ISSUE TITLE
MissingPluginException while trying to get all UPI apps

### ISSUE THREAD

**Issue by reeteshranjan** [drenther/upi_pay#10]
E/flutter ( 7357): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getAllUpiApps on channel com.az.upi_india)
E/flutter ( 7357): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 7357): <asynchronous suspension>
E/flutter ( 7357): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 7357): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:347:40)
E/flutter ( 7357): #3      UpiIndia.getAllUpiApps (package:upi_india/upi_india.dart:23:24)

Android Version 6

Is there any other Kotlin/Java/AndroidManifest.xml configuration/modification required other than including the package?

**Comment by pepsighan** [comment]
This is just a hunch, try closing the flutter app and run the app again (as plugins are not loaded dynamically during runtime). 

If this does not help refresh the dependencies as they might not have been downloaded and initialized properly.

**Comment by reeteshranjan** [comment]
Sorry wrong stack trace. Was evaluating upi_pay and upi_india packages and the trace is from upi_india (though similar exception was received there). Will try the reloading.
