### ISSUE TITLE
MiPay package identifier has changed causing it to not get detected

### ISSUE THREAD

**Issue by reeteshranjan** [drenther/upi_pay#13]
In debugging today it's seen that it has changed and does not match what's in the code

**Comment by mdazharuddin1011999** [comment]
Actually the MiPay available in **Playstore** has package name of **com.mipay.in.wallet** while the MiPay available in **GetApps** and shipped by default with MIUI 11 has a package name of **com.mipay.wallet.in**. Also the Playstore version is not compatible with my Redmi Note 4 with Android 7.0

**Comment by mdazharuddin1011999** [comment]
Maybe we should keep both of them. I checked in another Redmi phone and the playstore version is not compatible in that one either.

**Comment by drenther** [comment]
I think @mdazharuddin1011999 is right. Makes sense why we had the one earlier. I used to have a Redmi phone then and now a different one causing the blindsidedness in both the cases.

Thanks @mdazharuddin1011999 for pointing it out.

**Comment by mdazharuddin1011999** [comment]
Also the "Empty" transaction ID problem as mentioned by @reeteshranjan in #14  is present in the GetApps version too.

**Comment by reeteshranjan** [comment]
I would say that this should be fixed gradually and structurally. Basically, we should label the apps in the code with their corresponding play store, so that they are represented properly. Idea of labelling the with the corresponding play store is also about keeping it useful for everyone. Not everyone will have a Redmi phone, and they may not be able to clearly work out which Mi Pay to use in their code etc.

Several vendors have their own play stores. I use a Vivo Android 8 phone and its Vivo play store has differences from Google's play store as well. So gradual and structured method will work best, and to begin with I have mapped out several Google play store apps in #17 latest commits.

**Comment by drenther** [comment]
Closing this as we have handled it in the way we deem ideal in #17

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@azhar1038
