### ISSUE TITLE
Support for other UPI apps

### ISSUE THREAD

**Issue by reeteshranjan** [drenther/upi_pay#15]
For my project, I have been working on supporting several other apps available on at least Android today. For several apps it has been straight forward to support them after discovering their package names as returned by OS. I've 20+ apps (beyond those currently supported by upi_pay) supported in my version (not yet committed to my fork as I am continuing testing).

One major fundamental change that came out of this experimentation is that some apps do not like the URL encoding of `pa`. For example, for a given `pa` with value `abc@upi`, it gets encoded as `abc%40upi` and some of the apps extracted it as `abc 40upi` (space comes in for %) resulting in a failed transaction workflow. I changed the URI building to not use encoding for at least the `pa` parameter. It's a decision that works for me as I can handle my own client code and maintaining it is possible.

The question I have for the main developers is: is this project looking to integrate such work? If so, I'll create pull requests.

**Comment by reeteshranjan** [comment]
Submitting summary of my experiments of trying to extend the library on various UPI apps on Android.

**Working Apps (19)**

_Apps that properly integrate to the point of sending back usable transaction data._

Amazon Pay, Axis Pay, BHIM Baroda Pay, BHIM, BHIM Cent UPI (Central Bank of India), Cointab, BHIM DCB UPI, Google Pay, iMobile, IndusPay, MahaUPI (Maharashtra Bank), Mobikwik, BHIM Oriental Pay, PayTM, Paywiz, Phone Pe, BHIM PSB, BHIM SBI Pay, Yes Pay

**Did not work for me apps (10)**

_Apps that either do not understand the calls, or do not seem to support intents, or have unstable functionality, or do not send back usable transaction data post debit, or do not respond at all post debit._

Airtel Pay, IDFC UPI, IndianBank UPI, KBL UPI, KVB Pay, LVB Upaay, Mi Pay, RBL UPI, SyndUPI, UCO UPI

**Heading towards rejected/Under trial (8)**:

_These seemed to exhibit what one would think as temporary issues and would be tested further again. Issues range from not getting the SMS authentication going to payment not getting through._

Bandhan Bank, BOI UPI, CORP UPI, CSB Pay, Freecharge, Truecaller, UltraCash, Vijaya UPI

**Comment by reeteshranjan** [comment]
I completed the above study to end up with this:

**Working Apps (21)**

Amazon Pay, Axis Pay, BHIM Baroda Pay, BHIM, BHIM Cent UPI (Central Bank of India), Cointab, BHIM CORP UPI, BHIM DCB UPI, Freecharge, Google Pay, iMobile, IndusPay, MahaUPI (Maharashtra Bank), Mobikwik, BHIM Oriental Pay, PayTM, Paywiz, Phone Pe, BHIM PSB, BHIM SBI Pay, Yes Pay

**Did not work for me apps (16)**

Airtel Pay (#16 ), Bandhan Bank, BOI UPI (Bank of India), CSB Pay, IDFC UPI, IndianBank UPI, KBL UPI, KVB Pay, LVB Upaay, Mi Pay (#14 ), RBL UPI, SyndUPI, Truecaller (it's been persistently failing to do the SMS verification for me), UCO UPI, UltraCash, Vijaya UPI

There may be more apps on Play Store; but these are the ones that showed up when searching for BHIM/UPI.

**Comment by drenther** [comment]
Hey, thanks for the extensive details in the issue. And apologies for replying late. I would say let's take it one step at a time and maybe go for the 21 working apps initially only. What do you guys think? @reeteshranjan @pepsighan

**Comment by drenther** [comment]
The problem with that is removal of Airtel Pay app, which is a breaking change.

**Comment by reeteshranjan** [comment]
> The problem with that is removal of Airtel Pay app, which is a breaking change.

Please do verify for yourself. More devices we could test and keep the supported list current, it would be something worthy of eyes-closed integration.

**Comment by pepsighan** [comment]
@drenther Yeah, we can go incrementally with what is working best and any breaking change can be postponed for a major version when things settle down.

**Comment by reeteshranjan** [comment]
In the following comments I am documenting the detailed report on testing of all apps that will help reviewing the the pull request I'm going to create

**Comment by reeteshranjan** [comment]
### New apps working on Android

#### Criteria for being termed as working

- App launches
- App presents the payment form pre-filled with parameters specified in Intent call
- App completes the payment at least once
- App automatically returns to caller app
- Caller app receives at least one or both of: transaction ID, approval Ref

#### List of New Apps passing the criteria (16)

1. BHIM Baroda Pay
2. BHIM Cent UPI
3. BHIM CORP UPI
4. BHIM DCB UPI
5. BHIM IndusPay UPI
6. BHIM Oriental Pay
7. Bhim Paywiz v2
8. BHIM PSB
9. BHIM Yes Pay
10. BPay
11. Cointab
12. Freecharge
13. iMobile (Was not listed in valid applications)
14. KhaaliJeb
15. MahaUPI
16. Mobikwik

**Comment by reeteshranjan** [comment]
### New apps that get setup but fail to integrate properly

#### Criteria

- The app gets the UPI setup (mobile verification, and discovering linked bank accounts) working
- The app shows up as an UPI app during discovery
- The app gets launched through the Intent invocation
- Post the invoked launch, integration fails with different reasons to the extent that this app is not usable (as per the testing done so far)

#### Retention towards further testing

The code that detects these apps' package names is retained for avoiding repetitive work around recognising these apps and allowing further testing on other devices before ruling them out.

These are commented out while being retained in the list of valid apps in the commit for the upcoming pull request, so it's straightforward to enable them back and test further.

#### List of these apps (11)

1. BHIM AuPay: Sends back empty values for transaction ID and approval Ref in response after payment goes through
2. BHIM Bandhan UPI: While trying to pay says "something went wrong" and this error persists across retries
3. BHIM CSB-UPI: Hangs indefinitely on its opening view when launched
4. BHIM IndianBank UPI: Payment functionality does not work stably and errors out in unpredictable manner
5. BHIM KBL UPI: Says "mandatory values are missing" when launched, for every try made
6. BHIM KVB UPI: Does not show a pre-filled payment form when launched
7. BHIM LVB Upaay: Payment succeeds but does not return to the caller app
8. BHIM RBL Pay: Keeps trying to log in in a loop when launched
9. BHIM UCO UPI: Says "mandatory values are missing" when launched, for every try made
10. BHIM@Synd UPI: While making payment give a functional error and payment does not succeed, for each try made
11. UltraCash: Says "transaction canceled" for each try made

**Comment by reeteshranjan** [comment]
### New apps that show up as UPI apps in discovery but do not get setup

#### Criteria

- Intent call to find UPI apps include these apps
- Setup steps to get to linking UPI accounts to a VPA do not get completed

#### Retention towards further testing

The code that detects these apps' package names is retained for avoiding repetitive work around recognising these apps and allowing further testing on other devices before ruling them out.

These are commented out while being retained in the list of valid apps in the commit for the upcoming pull request, so it's straightforward to enable them back and test further.

#### List of these apps (5)

1. BHIM BOI UPI: Mobile number verification fails, for all tries made
2. BHIM Equitas UPI: Mobile number verification fails, for all tries made
3. BHIM Vijaya UPI App: Mobile number verification fails, for all tries made
3. PayZapp: Mobile number verification fails, for all tries made
4. Realme PaySa: Mobile number verification fails, for all tries made

**Comment by reeteshranjan** [comment]
### Apps not included in code

#### Reason of not including

These apps are mentioned in the various lists in the links shared earlier. However; they are not included in code for various reasons listed below, and are captured here so anyone else can see if they have a workaround/solution for the reasons mentioned and test them towards integrating.

#### List of these apps
1.  BHIM IDFC FIRST Bank UPI App: supports only merchants (could not test as I am not one)
1. BHIM LOTZA MERCHANT App: supports only merchants (could not test as I am not one)
1. BHIM PNB: only for Union Bank of India/Oriental Bank of Commerce customers
1. BHIM United UPI Pay: only for Union Bank of India/Oriental Bank of Commerce customers
1. CUB mBank Plus: only for CUB customers
1. DBS India: only for DBS customers
1. Kotak Bank App: only for Kotak bank customers
1. OMEGAPAY: does not register itself as an UPI app (at least on my Android 8 device)
1. SIB UPI-POS: only for South Indian Bank customers

**Comment by reeteshranjan** [comment]
Please wait for another commit tomorrow before reviewing this pull request. @drenther @pepsighan

**Comment by reeteshranjan** [comment]
I have completed my commits on this one. @drenther @pepsighan

**Comment by reeteshranjan** [comment]
In their latest release, Jio has added support for UPI payment. Did not test it out yet. Adding here for tracking.

**Comment by reeteshranjan** [comment]
Please see and review https://github.com/drenther/upi_pay/pull/17.

**Comment by reeteshranjan** [comment]
See https://github.com/reeteshranjan/upi_pay/blob/master/APPS.md for latest verification status of a number of apps across android and ios.

**Comment by drenther** [comment]
A whole plethora of apps are being supported now since the merge of #17

The updated list available here - [APPS.md](https://github.com/drenther/upi_pay/blob/master/APPS.md)
