### ISSUE TITLE
Kotlin Type Mismatch

### ISSUE THREAD

**Issue by masterashu** [drenther/upi_pay#20]
I am getting the following error on android compile version 30
```
e: D:\Programs\Pub\Cache\hosted\pub.dartlang.org\upi_pay-0.2.4\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (155, 34):
 Type mismatch: inferred type is String? but String was expected```

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@masterashu
