### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by GJJ2019** [drenther/upi_pay#23]
This is a request to add support for null safety to **package:upi_pay**.

**Comment by drenther** [comment]
Merged and resolved with #27 and live from v1.0.0 on pub

**Comment by reeteshranjan** [comment]
Thanks @GJJ2019 for the hurray! 🙂

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@GJJ2019
