### ISSUE TITLE
Using old version of universal_io library

### ISSUE THREAD

**Issue by thakurmayur** [drenther/upi_pay#28]
This is not an issue but as you are using old version of **universal_io**, it is getting **incompatible with cryptography ^2.0.1**.  Although cryptography is not part of this library but most of the flutter apps uses this to support GCM encryption. If you update the universal_io to version **2.0.4** it will get resolved.

**Comment by reeteshranjan** [comment]
Part of pull request #27

**Comment by drenther** [comment]
Closing this since #27 addressed this and was merged and release in v1.0.0 of the package!

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@thakurmayur
