### ISSUE TITLE
Cannot get all UPI apps in list of Installed Apps

### ISSUE THREAD

**Issue by madhuraadawadkar** [drenther/upi_pay#3]
I currently have Google Pay, PhonePe, PayTM and Truecaller insalled on my phone,
But when I invoke UpiPay.getInstalledUpiApplications(), I only get 2 in the list of installed apps: Google Pay and True Caller.
Am I missing something?

**Comment by pepsighan** [comment]
`UpiPay.getInstalledUpiApplications()` only lists those UPI apps which have subscribed to the UPI android intent. 

Just to check, have you logged in your UPI accounts in PhonePe and PayTM?

**Comment by madhuraadawadkar** [comment]
Oh, my bad!
I had downloaded the app but had not linked any UPI account on PhonePe. I did that, and now I can see it.
Thanks!!

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@madhuraadawadkar
