### ISSUE TITLE
google pay is not accepting payment

### ISSUE THREAD

**Issue by vinayvishnu725** [drenther/upi_pay#32]
i tried to make transaction on google pay its blocking , but with other UPI apps its working fine ...
my flutter verion is 1.22.5,

**Comment by reeteshranjan** [comment]
This is known behaviour for non-merchant payments since past few months. More details are available in README and APPS.md files in project directory. Please let us know if you need any more details post that.

**Comment by adityasreebysani** [comment]
transactions are failing on gpay even to merchant accounts.

I get this error :

"the transaction may be risky.For your safety ,it cant be completed at this time"

PhonePe, Paytm are working fine

**Comment by reeteshranjan** [comment]
@adityasreebysani the package currently does not support merchant payments.

Please see [initiateTransaction](https://pub.dev/documentation/upi_pay/latest/upi_pay/UpiPay/initiateTransaction.html) documentation. It does not allow you to provide merchant payment parameters required by UPI linking specification implemented by this package.

As per UPI specifications, for merchant payments one needs to pass merchant ID as well as a signature of the whole request data. See section 1.3 in [UPI linking specification](https://github.com/reeteshranjan/upi_pay/files/6338127/UPI.Linking.Specs_ver.1.6.pdf).

If you want more information on why this is being done, please see https://github.com/reeteshranjan/upi_pay/files/6338127/UPI.Linking.Specs_ver.1.6.pdf.

**Comment by reeteshranjan** [comment]
@adityasreebysani @vinayvishnu725 please follow #38

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@adityasreebysani @vinayvishnu725
