### ISSUE TITLE
transaction amount exceed limt showing solution? please?

### ISSUE THREAD

**Issue by bashadev21** [drenther/upi_pay#35]
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

**Comment by drenther** [comment]
Transaction amount exceeding limit is not something the plugin can take care of.

**Comment by bashadev21** [comment]
i tried lots like upi india plugins same shows in gpay can you please guide me

**Comment by reeteshranjan** [comment]
@bashadev21 please go through README and APPS.md. Relevant information is documented in there.

**Comment by reeteshranjan** [comment]
@bashadev21 please follow #38 for further updates

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@bashadev21
