### ISSUE TITLE
Gpay only , does not accepting payment ...

### ISSUE THREAD

**Issue by vinayvishnu725** [drenther/upi_pay#37]
Gpay is not acce[ting the payment , shows warning " this transaction may be risky for your safety it cant be completed " . may I get the solution ...

**Comment by vinayvishnu725** [comment]
am using the latest version ^1.0.1 am trying to make transaction , using merchant Upi address , but still G-pay is not accepting payments ,  showing "this transaction may be risky for your safety it cant be completed" , as u documentation for ^1.0.1 , signature and merchant code is required , can we try to edit or implement this signature and merchant code in latest version ... or any other solution , plzzz...

**Comment by reeteshranjan** [comment]
@vinayvishnu725 
1. Merchant code implies that the app you are developing will make the user payment go to a merchant account i.e. bank account related to your service/company that you are building the app for. Do you have such use case?
2. Work on merchant account payments is yet to be done. I'm currently working on a project that will help me test such transactions. It is expected this month, so hopefully I can do a release in August that will support merchant payments.

**Comment by vinayvishnu725** [comment]
@reeteshranjan thank you for the response , we'll keep in touch with this package .

**Comment by reeteshranjan** [comment]
Please follow the dev ticket #38 . Closing this issue.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@vinayvishnu725
