### ISSUE TITLE
Some android 11 device get App not found error (0 upi apps found )

### ISSUE THREAD

**Issue by Ak23598** [drenther/upi_pay#40]

**Comment by drenther** [comment]
Bug reports not following the template will be closed without further investigation.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@Ak23598
