### ISSUE TITLE
risk threshold exceeded hdfc app

### ISSUE THREAD

**Issue by sravan1432** [drenther/upi_pay#45]
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Play Store: [e.g. Google, Mi, Vivo]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

**Comment by sravan1432** [comment]
![Screenshot_20211121_152024](https://user-images.githubusercontent.com/94783950/142758518-dc695061-cfcc-402d-b13c-a46ec745bd27.jpg)

**Comment by drenther** [comment]
Issues without description or context will be immediately closed. Thank you!

**Comment by reeteshranjan** [comment]
@sravan1432 please check #38. It is the master ticket for the common security related issues people observe.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@sravan1432
