### ISSUE TITLE
iOS UPI app launch failure: Null check operator used on a null value

### ISSUE THREAD

**Issue by hardikvij195** [drenther/upi_pay#46]
Hi...I want to use this package on iOS but I am not able to open google pay and its throwing me this issue. Pls check 

iOS UPI app launch failure: Null check operator used on a null value

iOS UPI app launch failure: Null check operator used on a null value
flutter: iOS UPI app launch failure stack: #0      TransactionDetails.toString
package:upi_pay/src/transaction_details.dart:66
#1      UpiMethodChannel.launch
package:upi_pay/src/method_channel.dart:26
#2      IosTransactionHelper.transact
package:upi_pay/src/transaction.dart:57
#3      UpiTransactionHelper.transact
package:upi_pay/src/transaction.dart:22
#4      UpiPay.initiateTransaction
package:upi_pay/src/api.dart:73
#5      _ScreenState._onTap
package:test3/main.dart:95
#6      _ScreenState._appsGrid.<anonymous closure>.<anonymous closure>
package:test3/main.dart:319
#7      _ScreenState._appsGrid.<anonymous closure>.<anonymous closure>
package:test3/main.dart:319
#8      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:989
#9      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:182
#10     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:607
#11     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#12     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
#13     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#14     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:443
#15     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#16     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:287
#17     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#18     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338

Thanks in advance

**Comment by drenther** [comment]
Please stick to the issue template when filing bugs.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@hardikvij195

**Comment by hardikvij195** [comment]
Yea can be....i'll respond on ur twitter.
Thanks
@reeteshranjan
