### ISSUE TITLE
Not able to open any UPI in IOS.

### ISSUE THREAD

**Issue by AamilSilawat26** [drenther/upi_pay#47]
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Play Store: [e.g. Google, Mi, Vivo]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

### Additional context
@reeteshranjan  Hello, I have look into this plug in as i mentioned above some UPIs not showing because in device no-one UPI app was registered with account, Issue was solved but In IOS not able to open any UPI apps, Can you please help ?

**Comment by drenther** [comment]
Only raise issues for bug or enhancement related to the package and stick to the template to provide all necessary information. 

For any help or suggestions use the discussions panel.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@AamilSilawat26
