### ISSUE TITLE
Fetch a single app details

### ISSUE THREAD

**Issue by vjk10** [drenther/upi_pay#48]
Add a feature to fetch a single UPI application details.

**Comment by drenther** [comment]
Please stick to the template.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@vjk10
