### ISSUE TITLE
Mismatch txnId

### ISSUE THREAD

**Issue by dineshbalan001** [drenther/upi_pay#49]
Payment everything working properly but after the payment txnId(Transaction ID) is a mismatch. eg:- actual txnId is 201785931600 but get txnId is 0BE87358021B8B7939126F17997B08D9. Why does it show like this?

**Comment by drenther** [comment]
Only raise issues for bug or enhancement related to the package and stick to the template to provide all necessary information.

For any help or suggestions use the discussions panel.

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@dineshbalan001
