### ISSUE TITLE
await UpiPay.getInstalledUpiApplications() returning empty list

### ISSUE THREAD

**Issue by nilotpalkapri** [drenther/upi_pay#54]
### Describe the bug
This package was working fine till November 2021. After that await UpiPay.getInstalledUpiApplications() method returning empty list. Setting statusType: UpiApplicationDiscoveryAppStatusType.all returning applications but getting payment failure response(U09-Timeout). Is there anything need to be added in Androidmanifest.xml or MainActivity.kt?
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Play Store: [e.g. Google, Mi, Vivo]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

**Comment by drenther** [comment]
Check if the apps are supported as of now. All the supported apps and their status are listed under apps.md in the repo.

And please follow the bugs issue format otherwise the issue will be closed without any further action.

**Comment by nilotpalkapri** [comment]
Ok thanks for the response but yes I am trying with the supported apps but unfortunately not getting any solution. I am trying with PhonePe and Paytm.
 
Also I have tested by launching the upi url using url_launcher package, same issue is happening. Thats why I am confused about the issue. I have tested with the example app also, same problem.
 
If you please share any view on this issue, I will be thankful to you..
