### ISSUE TITLE
Unable to use because of Decimal 2.0

### ISSUE THREAD

**Issue by pryshrm** [drenther/upi_pay#55]
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Play Store: [e.g. Google, Mi, Vivo]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

**Comment by drenther** [comment]
Please follow the issue template. Or issues will be closed without action.
