### ISSUE TITLE
Add a sample video(gif) of transaction

### ISSUE THREAD

**Issue by piyushchauhan** [drenther/upi_pay#6]
Adding a transaction gif will help to gain more trust of developers on relying on this package.

**Comment by drenther** [comment]
We have GIF recording for both iOS and Android example implementation thanks @reeteshranjan

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@piyushchauhan
