### ISSUE TITLE
Execution failed for task ':upi_pay:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction

### ISSUE THREAD

**Issue by asifakhtar98** [drenther/upi_pay#61]
Running Gradle task 'assembleDebug'...
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (78, 42): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (83, 15): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?
e: C:\flutter\.pub-cache\hosted\pub.dartlang.org\upi_pay-1.0.1\android\src\main\kotlin\com\drenther\upi_pay\UpiPayPlugin.kt: (97, 34): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Activity?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':upi_pay:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Comment by drenther** [comment]
Duplicate issue. Closing.

**Comment by valery-lavrik** [comment]
@drenther     can I link to the original error?

**Comment by drenther** [comment]
#60
