### ISSUE TITLE
Whenever we open Any UPI app It's redirect to last app url.                                                                                                                                          

### ISSUE THREAD

**Issue by thakaredipali** [drenther/upi_pay#64]
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app
4. ...

### Environmental Details
- OS: [e.g. Android 11]
- Device: [e.g. OnePlus Nord]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm]
- Play Store: [e.g. Google, Mi, Vivo]
- Other UPI / Payment packages used in the app: [e.g. - razorpay_flutter]

**Comment by vishalsgithub** [comment]
**Same Issue**

I click on **PhonePay** or **Gpay** but it redirects to WhatsApp only

then I called this line

  **UpiPay.getInstalledUpiApplications(
          statusType: UpiApplicationDiscoveryAppStatusType.working)**

it returns only WhatsApp not any other installed UPI App. All UPI apps on my device are working.

**Environmental Details**

OS: [IOS 16.4.1]
Device: [Iphone XR]
Package Version: [1.0.0]
UPI Applications in the device: [GPay, PhonePay, Whatsapp]
Play Store: [Apple AppStore]
Other UPI / Payment packages used in the app: [NA]

**Comment by niravp-cliqbux** [comment]
> **Same Issue**
> 
> I click on **PhonePay** or **Gpay** but it redirects to WhatsApp only
> 
> then I called this line
> 
> **UpiPay.getInstalledUpiApplications( statusType: UpiApplicationDiscoveryAppStatusType.working)**
> 
> it returns only WhatsApp not any other installed UPI App. All UPI apps on my device are working.
> 
> **Environmental Details**
> 
> OS: [IOS 16.4.1] Device: [Iphone XR] Package Version: [1.0.0] UPI Applications in the device: [GPay, PhonePay, Whatsapp] Play Store: [Apple AppStore] Other UPI / Payment packages used in the app: [NA]

@vishalsgithub @reeteshranjan Getting same issue on my end too only for iOS. Is there any workaround?

Environmental Details

OS: [IOS 16.6.1]
Device: [Iphone XR]
Package Version: [1.0.1]
UPI Applications in the device: [GPay, PhonePay, Whatsapp]
Play Store: [Apple AppStore]
Other UPI / Payment packages used in the app: [NA]
