### ISSUE TITLE
Your money ha not been debited. You've exceeded the bank limit for this payment. Retry with a smaller amount.

### ISSUE THREAD

**Issue by rvharjinderbains** [drenther/upi_pay#69]
### Describe the bug
I am getting following issue when trying to pay from Google pay. 
"Your money ha not been debited. You've exceeded the bank limit for this payment. Retry with a smaller amount."
### To Reproduce
Steps to reproduce the behaviour:
1. Enter VPA
2. Trigger payment
3. Go to opened UPI app

### Expected behaviour
It should work however It is working when I am trying to pay directly from Google Pay

### Environmental Details
- OS: [e.g. Android 9]
- Device: [e.g. Vivo V 9]
- Package Version: [e.g. v1.0.0]
- UPI Applications in the device: [e.g. - GPay, Paytm and BHaratpay]
- Play Store: [Google]

**Comment by drenther** [comment]
Likely related to #38

**Comment by rvharjinderbains** [comment]
> Likely related to #38

It is not clear. Please make it more easy. Can you provide proper tutorial
