### ISSUE TITLE
UPI Pay returning invalid response for successful transactions

### ISSUE THREAD

**Issue by rsbthebest** [drenther/upi_pay#7]
Hi Team,

Am testing the UPI pay to collect the payments, and even after the successful transaction I am getting a failed response in the app.

I am using the same code we have in the example app for making the payment (just changes the UPI ID).

Here is the image of the response received:

![Annotation 2020-08-14 181637](https://user-images.githubusercontent.com/12830614/90250814-556f4580-de5a-11ea-9954-30af04f48262.png)

Please let me know if you need more details.

Regards,
Rajdeep Barad

**Comment by drenther** [comment]
Closing this!

**Comment by reeteshranjan** [comment]
@rsbthebest I saw this error once or twice in my testing; but failed to record it. Could you please let us know which app do you see this error with?

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@rsbthebest
