### ISSUE TITLE
When we can expect the Ios implementation?

### ISSUE THREAD

**Issue by dnsoumik** [drenther/upi_pay#8]

**Comment by drenther** [comment]
closing this. This is being tracked in #2

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@dnsoumik
