### ISSUE TITLE
 Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.

### ISSUE THREAD

**Issue by sunilshedge** [drenther/upi_pay#85]
Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file: C:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\flutter_upi_india-0.0.1\android\build.gradle. See

**Comment by drenther** [comment]
This is not `flutter_upi_india`. Please file issues in the correct repo.
