### ISSUE TITLE
Axis mobile app is not added due to which it’s not reflecting on the list

### ISSUE THREAD

**Issue by souryanair** [drenther/upi_pay#9]

**Comment by drenther** [comment]
Added in v0.2.3

**Comment by reeteshranjan** [comment]
Is https://github.com/drenther/upi_pay/issues/38 relevant and important for you?

If yes, could you please respond to my twitter thread with UPI and NPCI handles included in your response asking how these must be solved and how it helps you? https://twitter.com/reeteshr08/status/1488746633068089345

@souryanair
